version: '3.5'
services:
  localstack:
    hostname: localstack
    image: localstack/localstack:1.2.0
    networks:
      - backend
    ports:
      - "4566:4566"
      - "9000:9000"
    environment:
      - SERVICES=S3,SNS
      - DEFAULT-REGION=us-west-1
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/aws-local.sh:/docker-entrypoint-initaws.d/aws-local.sh
networks:
  backend:
    name: test-backend
    external: false
